### Site Settings ###
title               : skew 
description         : math and ai
# >- means to ignore newlines until "url:"
url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]

### Author Info ###
author:
  name              : skew
#  image             : https://bit.ly/2KCvgVJ
#  behance           : your_username
# dribbble          : your_username
#  email             : username@domain.com
#  facebook          : your_username
  github            : nunoskew
# gitlab            : your_username
# instagram         : your_username
  linkedin          : nunoskew 
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
  twitch            : skewpt 
  twitter           : nunoskew
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title

markdown: kramdown
kramdown:
  parse_block_html: true

### Collections ###
collections:
  math:
    output: true
    permalink: /math/:name
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type:  ["math","projects"]
    values:
      layout: "page"
#  - scope:
#      path: ""
#      type: "math" 
#    values:
#      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
